// @ts-nocheck
import * as __fd_glob_57 from "../content/docs/developers/decisions/supervisor-reliability.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/developers/decisions/memory-ranking.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/developers/decisions/mcp-auto-sync.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/developers/decisions/dynamic-tool-loading.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/developers/decisions/automation-safe-tools.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/reference/tools.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/reference/mcp-server.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/reference/environment-variables.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/reference/cli.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/reference/automation-schema.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/reference/app-manifest.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/reference/api.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/legal/terms-of-service.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/legal/privacy-policy.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/guides/terminal.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/guides/telegram-discord-bots.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/guides/self-improvement.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/guides/networking.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/guides/monitoring.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/guides/migrating-from-umbrel.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/guides/migrating-from-casaos.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/guides/media-stack.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/guides/backups.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/guides/automations.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/guides/app-store.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/guides/app-creation.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/guides/ai-assistant.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/integrations/vaultwarden.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/integrations/sonarr-radarr.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/integrations/qbittorrent.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/integrations/prowlarr.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/integrations/plex.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/integrations/pihole.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/integrations/overseerr.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/integrations/ollama.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/integrations/jellyfin.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/integrations/index.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/integrations/home-assistant.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/integrations/audiobookshelf.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/getting-started/installation.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/getting-started/first-conversation.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/getting-started/dashboard-tour.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/getting-started/configuration.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/developers/design-system.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/developers/contributing.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/developers/architecture.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/developers/adding-integrations.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/index.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/faq.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/changelog.mdx?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/developers/decisions/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/reference/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/legal/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/integrations/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/guides/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/getting-started/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/developers/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "developers/meta.json": __fd_glob_1, "getting-started/meta.json": __fd_glob_2, "guides/meta.json": __fd_glob_3, "integrations/meta.json": __fd_glob_4, "legal/meta.json": __fd_glob_5, "reference/meta.json": __fd_glob_6, "developers/decisions/meta.json": __fd_glob_7, }, {"changelog.mdx": __fd_glob_8, "faq.mdx": __fd_glob_9, "index.mdx": __fd_glob_10, "developers/adding-integrations.mdx": __fd_glob_11, "developers/architecture.mdx": __fd_glob_12, "developers/contributing.mdx": __fd_glob_13, "developers/design-system.mdx": __fd_glob_14, "getting-started/configuration.mdx": __fd_glob_15, "getting-started/dashboard-tour.mdx": __fd_glob_16, "getting-started/first-conversation.mdx": __fd_glob_17, "getting-started/installation.mdx": __fd_glob_18, "integrations/audiobookshelf.mdx": __fd_glob_19, "integrations/home-assistant.mdx": __fd_glob_20, "integrations/index.mdx": __fd_glob_21, "integrations/jellyfin.mdx": __fd_glob_22, "integrations/ollama.mdx": __fd_glob_23, "integrations/overseerr.mdx": __fd_glob_24, "integrations/pihole.mdx": __fd_glob_25, "integrations/plex.mdx": __fd_glob_26, "integrations/prowlarr.mdx": __fd_glob_27, "integrations/qbittorrent.mdx": __fd_glob_28, "integrations/sonarr-radarr.mdx": __fd_glob_29, "integrations/vaultwarden.mdx": __fd_glob_30, "guides/ai-assistant.mdx": __fd_glob_31, "guides/app-creation.mdx": __fd_glob_32, "guides/app-store.mdx": __fd_glob_33, "guides/automations.mdx": __fd_glob_34, "guides/backups.mdx": __fd_glob_35, "guides/media-stack.mdx": __fd_glob_36, "guides/migrating-from-casaos.mdx": __fd_glob_37, "guides/migrating-from-umbrel.mdx": __fd_glob_38, "guides/monitoring.mdx": __fd_glob_39, "guides/networking.mdx": __fd_glob_40, "guides/self-improvement.mdx": __fd_glob_41, "guides/telegram-discord-bots.mdx": __fd_glob_42, "guides/terminal.mdx": __fd_glob_43, "legal/privacy-policy.mdx": __fd_glob_44, "legal/terms-of-service.mdx": __fd_glob_45, "reference/api.mdx": __fd_glob_46, "reference/app-manifest.mdx": __fd_glob_47, "reference/automation-schema.mdx": __fd_glob_48, "reference/cli.mdx": __fd_glob_49, "reference/environment-variables.mdx": __fd_glob_50, "reference/mcp-server.mdx": __fd_glob_51, "reference/tools.mdx": __fd_glob_52, "developers/decisions/automation-safe-tools.mdx": __fd_glob_53, "developers/decisions/dynamic-tool-loading.mdx": __fd_glob_54, "developers/decisions/mcp-auto-sync.mdx": __fd_glob_55, "developers/decisions/memory-ranking.mdx": __fd_glob_56, "developers/decisions/supervisor-reliability.mdx": __fd_glob_57, });