services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - "9696:9696"
    volumes:
      - ./config:/config
    environment:
      - TZ=UTC
      - PUID=1000
      - PGID=1000
