// Generated by scripts/generate-desktop-icons.mjs.
const artwork: Readonly<Record<string, string>> = {
  "/dashboard/files": "/app-icons/files.svg",
  "/dashboard/media": "/app-icons/media.svg",
  "/dashboard/assistant": "/app-icons/assistant.svg",
  "/dashboard/terminal": "/app-icons/terminal.svg",
  "/dashboard/share": "/app-icons/share.svg",
  "/dashboard/settings": "/app-icons/settings.svg",
  "/dashboard/audiobooks": "/app-icons/audiobooks.svg",
  "/dashboard/containers": "/app-icons/services.svg",
  "/dashboard/apps": "/app-icons/app-store.svg",
  "/dashboard/automations": "/app-icons/automations.svg",
  "/dashboard/backups": "/app-icons/backups.svg",
  "/dashboard/intelligence": "/app-icons/intelligence.svg",
};

/** Exact Talome routes only: installed apps retain their own brand artwork. */
export function desktopAppArtwork(url: string): string | undefined {
  return artwork[url];
}
